name: WordPress Trigger Deploy

on:
  repository_dispatch:
    types: [wordpress_update]

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_DEPLOY_HOOK }}"
